In [1]:
import pandas as pd
#pd.set_option('display.float_format', lambda x: '{:.3f}'.format(x)) #Limiting floats output to 3 decimal points

import numpy as np
import warnings

train_realdata = pd.read_csv('C:/workspace/jeju/2020_jeju_creditcard/data/baselinedata.csv',index_col=0)
train_realdata.head()

In [2]:
corona = pd.read_csv('C:/workspace/jeju/2020_jeju_creditcard/data/Corona_timeprovince.csv')
corona.head()
corona_real = corona[corona.date<="2020-04-30"]

is_thirtyone = corona_real['date'].isin(['2020-01-31','2020-02-29','2020-03-31','2020-04-30'])
corona_real = corona_real[is_thirtyone]
corona_real

corona_real.rename(columns={'province':'CARD_SIDO_NM'},inplace=True)

corona_real = corona_real.sort_values(['CARD_SIDO_NM','date'])


corona_real

            date  time       CARD_SIDO_NM  confirmed  released  deceased
188   2020-01-31    16              Busan          0         0         0
681   2020-02-29    16              Busan         80         0         0
1208  2020-03-31     0              Busan        119        87         3
1718  2020-04-30     0              Busan        137       116         3
197   2020-01-31    16  Chungcheongbuk-do          0         0         0
690   2020-02-29    16  Chungcheongbuk-do         10         0         0
1217  2020-03-31     0  Chungcheongbuk-do         44        22         0
1727  2020-04-30     0  Chungcheongbuk-do         45        41         0
198   2020-01-31    16  Chungcheongnam-do          0         0         0
691   2020-02-29    16  Chungcheongnam-do         55         0         0
1218  2020-03-31     0  Chungcheongnam-do        128        90         0
1728  2020-04-30     0  Chungcheongnam-do        143       127         0
189   2020-01-31    16              Daegu          0         0         0
682   2020-02-29    16              Daegu       2236         3        10
1209  2020-03-31     0              Daegu       6684      3946       114
1719  2020-04-30     0              Daegu       6852      6144       172
192   2020-01-31    16            Daejeon          0         0         0
685   2020-02-29    16            Daejeon         13         0         0
1212  2020-03-31     0            Daejeon         36        18         0
1722  2020-04-30     0            Daejeon         40        35         0
196   2020-01-31    16         Gangwon-do          0         0         0
689   2020-02-29    16         Gangwon-do          7         0         0
1216  2020-03-31     0         Gangwon-do         36        23         1
1726  2020-04-30     0         Gangwon-do         53        40         2
191   2020-01-31    16            Gwangju          0         0         0
684   2020-02-29    16            Gwangju          9         2         0
1211  2020-03-31     0            Gwangju         20        14         0
1721  2020-04-30     0            Gwangju         30        27         0
195   2020-01-31    16        Gyeonggi-do          5         0         0
688   2020-02-29    16        Gyeonggi-do         82         8         1
...          ...   ...                ...        ...       ...       ...
1222  2020-03-31     0   Gyeongsangnam-do         96        67         0
1732  2020-04-30     0   Gyeongsangnam-do        117        97         0
190   2020-01-31    16            Incheon          1         0         0
683   2020-02-29    16            Incheon          6         1         0
1210  2020-03-31     0            Incheon         64        16         0
1720  2020-04-30     0            Incheon         93        68         0
203   2020-01-31    16            Jeju-do          0         0         0
696   2020-02-29    16            Jeju-do          2         0         0
1223  2020-03-31     0            Jeju-do          9         3         0
1733  2020-04-30     0            Jeju-do         13         8         0
199   2020-01-31    16       Jeollabuk-do          1         0         0
692   2020-02-29    16       Jeollabuk-do          5         1         0
1219  2020-03-31     0       Jeollabuk-do         13         7         0
1729  2020-04-30     0       Jeollabuk-do         18        11         0
200   2020-01-31    16       Jeollanam-do          0         0         0
693   2020-02-29    16       Jeollanam-do          3         0         0
1220  2020-03-31     0       Jeollanam-do          9         3         0
1730  2020-04-30     0       Jeollanam-do         15        11         0
194   2020-01-31    16             Sejong          0         0         0
687   2020-02-29    16             Sejong          1         0         0
1214  2020-03-31     0             Sejong         46        12         0
1724  2020-04-30     0             Sejong         46        38         0
187   2020-01-31    16              Seoul          4         0         0
680   2020-02-29    16              Seoul         77         9         0
1207  2020-03-31     0              Seoul        450       107         0
1717  2020-04-30     0              Seoul        633       453         2
193   2020-01-31    16              Ulsan          0         0         0
686   2020-02-29    16              Ulsan         17         0         0
1213  2020-03-31     0              Ulsan         39        19         0
1723  2020-04-30     0              Ulsan         43        37         1

[68 rows x 6 columns]

In [3]:
corona_real = corona_real.drop(columns= ['released','deceased','time'])

In [4]:
corona_real.replace(['Seoul','Gyeonggi-do','Gyeongsangnam-do','Daegu','Incheon','Chungcheongnam_do','Gyeongsangbuk-do','Busan','Daejeon','Gwangju','Chungcheongbuk-do','Jeollabuk-do','Ulsan','Jeollanam-do','Sejong','Gangwon-do','Jeju-do','Chungcheongnam-do'],['서울','경기','경남','대구','인천','충남','경북','부산','대전','광주','충북','전북','울산','전남','세종','강원','제주','충남'],inplace=True)

In [5]:
corona_real

            date CARD_SIDO_NM  confirmed
188   2020-01-31           부산          0
681   2020-02-29           부산         80
1208  2020-03-31           부산        119
1718  2020-04-30           부산        137
197   2020-01-31           충북          0
690   2020-02-29           충북         10
1217  2020-03-31           충북         44
1727  2020-04-30           충북         45
198   2020-01-31           충남          0
691   2020-02-29           충남         55
1218  2020-03-31           충남        128
1728  2020-04-30           충남        143
189   2020-01-31           대구          0
682   2020-02-29           대구       2236
1209  2020-03-31           대구       6684
1719  2020-04-30           대구       6852
192   2020-01-31           대전          0
685   2020-02-29           대전         13
1212  2020-03-31           대전         36
1722  2020-04-30           대전         40
196   2020-01-31           강원          0
689   2020-02-29           강원          7
1216  2020-03-31           강원         36
1726  2020-04-30           강원         53
191   2020-01-31           광주          0
684   2020-02-29           광주          9
1211  2020-03-31           광주         20
1721  2020-04-30           광주         30
195   2020-01-31           경기          5
688   2020-02-29           경기         82
...          ...          ...        ...
1222  2020-03-31           경남         96
1732  2020-04-30           경남        117
190   2020-01-31           인천          1
683   2020-02-29           인천          6
1210  2020-03-31           인천         64
1720  2020-04-30           인천         93
203   2020-01-31           제주          0
696   2020-02-29           제주          2
1223  2020-03-31           제주          9
1733  2020-04-30           제주         13
199   2020-01-31           전북          1
692   2020-02-29           전북          5
1219  2020-03-31           전북         13
1729  2020-04-30           전북         18
200   2020-01-31           전남          0
693   2020-02-29           전남          3
1220  2020-03-31           전남          9
1730  2020-04-30           전남         15
194   2020-01-31           세종          0
687   2020-02-29           세종          1
1214  2020-03-31           세종         46
1724  2020-04-30           세종         46
187   2020-01-31           서울          4
680   2020-02-29           서울         77
1207  2020-03-31           서울        450
1717  2020-04-30           서울        633
193   2020-01-31           울산          0
686   2020-02-29           울산         17
1213  2020-03-31           울산         39
1723  2020-04-30           울산         43

[68 rows x 3 columns]

In [6]:
n = corona_real.CARD_SIDO_NM.nunique()
j=2
for i in range(1,n):
        corona_real.iloc[4*i-3,j] = corona_real.iloc[4*i-3,j] - corona_real.iloc[4*i -4,j]
        corona_real.iloc[4*i-2,j] = corona_real.iloc[4*i-2,j] - corona_real.iloc[4*i -3,j]- corona_real.iloc[4*i -4,j]
        corona_real.iloc[4*i-1,j] = corona_real.iloc[4*i-1,j] - corona_real.iloc[4*i -2,j]- corona_real.iloc[4*i -3,j]- corona_real.iloc[4*i -4,j]
corona_real

            date CARD_SIDO_NM  confirmed
188   2020-01-31           부산          0
681   2020-02-29           부산         80
1208  2020-03-31           부산         39
1718  2020-04-30           부산         18
197   2020-01-31           충북          0
690   2020-02-29           충북         10
1217  2020-03-31           충북         34
1727  2020-04-30           충북          1
198   2020-01-31           충남          0
691   2020-02-29           충남         55
1218  2020-03-31           충남         73
1728  2020-04-30           충남         15
189   2020-01-31           대구          0
682   2020-02-29           대구       2236
1209  2020-03-31           대구       4448
1719  2020-04-30           대구        168
192   2020-01-31           대전          0
685   2020-02-29           대전         13
1212  2020-03-31           대전         23
1722  2020-04-30           대전          4
196   2020-01-31           강원          0
689   2020-02-29           강원          7
1216  2020-03-31           강원         29
1726  2020-04-30           강원         17
191   2020-01-31           광주          0
684   2020-02-29           광주          9
1211  2020-03-31           광주         11
1721  2020-04-30           광주         10
195   2020-01-31           경기          5
688   2020-02-29           경기         77
...          ...          ...        ...
1222  2020-03-31           경남         37
1732  2020-04-30           경남         21
190   2020-01-31           인천          1
683   2020-02-29           인천          5
1210  2020-03-31           인천         58
1720  2020-04-30           인천         29
203   2020-01-31           제주          0
696   2020-02-29           제주          2
1223  2020-03-31           제주          7
1733  2020-04-30           제주          4
199   2020-01-31           전북          1
692   2020-02-29           전북          4
1219  2020-03-31           전북          8
1729  2020-04-30           전북          5
200   2020-01-31           전남          0
693   2020-02-29           전남          3
1220  2020-03-31           전남          6
1730  2020-04-30           전남          6
194   2020-01-31           세종          0
687   2020-02-29           세종          1
1214  2020-03-31           세종         45
1724  2020-04-30           세종          0
187   2020-01-31           서울          4
680   2020-02-29           서울         73
1207  2020-03-31           서울        373
1717  2020-04-30           서울        183
193   2020-01-31           울산          0
686   2020-02-29           울산         17
1213  2020-03-31           울산         39
1723  2020-04-30           울산         43

[68 rows x 3 columns]

In [7]:
corona_real.CARD_SIDO_NM.nunique()

17

In [8]:
corona_real['year'] = corona_real['date'].astype(str).str[:4]
corona_real['month'] = corona_real['date'].astype(str).str[5:7]
corona_real['month'] = corona_real['month'].astype(int)
corona_real['month'] = corona_real['month'].astype(str)

corona_real = corona_real.drop(columns=['date'])

In [9]:
corona_real

     CARD_SIDO_NM  confirmed  year month
188            부산          0  2020     1
681            부산         80  2020     2
1208           부산         39  2020     3
1718           부산         18  2020     4
197            충북          0  2020     1
690            충북         10  2020     2
1217           충북         34  2020     3
1727           충북          1  2020     4
198            충남          0  2020     1
691            충남         55  2020     2
1218           충남         73  2020     3
1728           충남         15  2020     4
189            대구          0  2020     1
682            대구       2236  2020     2
1209           대구       4448  2020     3
1719           대구        168  2020     4
192            대전          0  2020     1
685            대전         13  2020     2
1212           대전         23  2020     3
1722           대전          4  2020     4
196            강원          0  2020     1
689            강원          7  2020     2
1216           강원         29  2020     3
1726           강원         17  2020     4
191            광주          0  2020     1
684            광주          9  2020     2
1211           광주         11  2020     3
1721           광주         10  2020     4
195            경기          5  2020     1
688            경기         77  2020     2
...           ...        ...   ...   ...
1222           경남         37  2020     3
1732           경남         21  2020     4
190            인천          1  2020     1
683            인천          5  2020     2
1210           인천         58  2020     3
1720           인천         29  2020     4
203            제주          0  2020     1
696            제주          2  2020     2
1223           제주          7  2020     3
1733           제주          4  2020     4
199            전북          1  2020     1
692            전북          4  2020     2
1219           전북          8  2020     3
1729           전북          5  2020     4
200            전남          0  2020     1
693            전남          3  2020     2
1220           전남          6  2020     3
1730           전남          6  2020     4
194            세종          0  2020     1
687            세종          1  2020     2
1214           세종         45  2020     3
1724           세종          0  2020     4
187            서울          4  2020     1
680            서울         73  2020     2
1207           서울        373  2020     3
1717           서울        183  2020     4
193            울산          0  2020     1
686            울산         17  2020     2
1213           울산         39  2020     3
1723           울산         43  2020     4

[68 rows x 4 columns]

In [10]:
corona_real.to_csv('C:/workspace/jeju/2020_jeju_creditcard/data/Corona_until_april.csv',encoding='EUC-KR')

In [11]:
corona_july = pd.read_csv('C:/workspace/jeju/2020_jeju_creditcard/data/corona_july.csv')

In [12]:
corona_july

    Unnamed: 0        date           province  confirmed
0         1718  2020-07-31              Seoul         62
1         1719  2020-07-31              Busan         62
2         1720  2020-07-31              Daegu         93
3         1721  2020-07-31            Incheon         31
4         1722  2020-07-31            Gwangju         31
5         1723  2020-07-31            Daejeon         31
6         1724  2020-07-31              Ulsan         31
7         1725  2020-07-31             Sejong         31
8         1726  2020-07-31        Gyeonggi-do         80
9         1727  2020-07-31         Gangwon-do         31
10        1728  2020-07-31  Chungcheongbuk-do         31
11        1729  2020-07-31  Chungcheongnam-do         62
12        1730  2020-07-31       Jeollabuk-do         31
13        1731  2020-07-31       Jeollanam-do         31
14        1732  2020-07-31   Gyeongsangbuk-do         31
15        1733  2020-07-31   Gyeongsangnam-do         62
16        1734  2020-07-31            Jeju-do          0

In [13]:
corona_july = corona_july.drop('Unnamed: 0',axis=1)

In [14]:
corona_july

          date           province  confirmed
0   2020-07-31              Seoul         62
1   2020-07-31              Busan         62
2   2020-07-31              Daegu         93
3   2020-07-31            Incheon         31
4   2020-07-31            Gwangju         31
5   2020-07-31            Daejeon         31
6   2020-07-31              Ulsan         31
7   2020-07-31             Sejong         31
8   2020-07-31        Gyeonggi-do         80
9   2020-07-31         Gangwon-do         31
10  2020-07-31  Chungcheongbuk-do         31
11  2020-07-31  Chungcheongnam-do         62
12  2020-07-31       Jeollabuk-do         31
13  2020-07-31       Jeollanam-do         31
14  2020-07-31   Gyeongsangbuk-do         31
15  2020-07-31   Gyeongsangnam-do         62
16  2020-07-31            Jeju-do          0

In [16]:
corona_july['year'] = corona_july['date'].astype(str).str[:4]
corona_july['month'] = corona_july['date'].astype(str).str[5:7]
corona_july['month'] = corona_july['month'].astype(int)
corona_july['month'] = corona_july['month'].astype(str)

corona_july = corona_july.drop(columns=['date'])

In [17]:
corona_july

             province  confirmed  year month
0               Seoul         62  2020     7
1               Busan         62  2020     7
2               Daegu         93  2020     7
3             Incheon         31  2020     7
4             Gwangju         31  2020     7
5             Daejeon         31  2020     7
6               Ulsan         31  2020     7
7              Sejong         31  2020     7
8         Gyeonggi-do         80  2020     7
9          Gangwon-do         31  2020     7
10  Chungcheongbuk-do         31  2020     7
11  Chungcheongnam-do         62  2020     7
12       Jeollabuk-do         31  2020     7
13       Jeollanam-do         31  2020     7
14   Gyeongsangbuk-do         31  2020     7
15   Gyeongsangnam-do         62  2020     7
16            Jeju-do          0  2020     7

In [18]:
corona_july.rename(columns={'province':'CARD_SIDO_NM'},inplace=True)

In [20]:
corona_july.replace(['Seoul','Gyeonggi-do','Gyeongsangnam-do','Daegu','Incheon','Chungcheongnam_do','Gyeongsangbuk-do','Busan','Daejeon','Gwangju','Chungcheongbuk-do','Jeollabuk-do','Ulsan','Jeollanam-do','Sejong','Gangwon-do','Jeju-do','Chungcheongnam-do'],['서울','경기','경남','대구','인천','충남','경북','부산','대전','광주','충북','전북','울산','전남','세종','강원','제주','충남'],inplace=True)

In [22]:
corona_july.to_csv('C:/workspace/jeju/2020_jeju_creditcard/data/Corona_july_predicted.csv',encoding='EUC-KR')

train_realdata.dtypes

corona_real.dtypes

merge = pd.merge(train_realdata, corona_real, left_on = ['CARD_SIDO_NM','year','month'], right_on = ['CARD_SIDO_NM','year','month'], how='left') 
merge = merge.fillna(0)

merge.to_csv('C:/workspace/jeju/2020_jeju_creditcard/data/Corona_added.csv')